### ISSUE TITLE
src/events/publish-old.js uses aws-sdk, but aws-sdk not in dependencies of this module

### ISSUE THREAD

**Issue by filmaj** [architect/functions#42]
hit this while trying to set up a proxy to a spa. my get-index route:

```
let arc = require('@architect/functions');
exports.handler = arc.http.proxy({spa:true})
```

relevant section of the get-index route's `package.json`:

```
grep -B 1 -A 1 functions package.json
  "dependencies": {
    "@architect/functions": "^3.2.2"
  }
```

when i run the above in sandbox, i get the following stack:

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'aws-sdk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/maj/src/arctonic/src/http/get-index/node_modules/@architect/functions/src/events/publish-old.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

looks like `src/events/publish-old.js` uses `aws-sdk`. currently it is set as a dev dependency in this module's `package.json`. probably should move it to a full dependency?

**Comment by brianleroux** [comment]
Ah, no, but we need to doc how to handle this locally. (AWS SDK is global to lambda so you don't need to add the weight)

**Comment by brianleroux** [comment]
I `npm install -g aws-sdk` but there must be a better way locally

**Comment by filmaj** [comment]
`npm install -g aws-sdk` didn't work to fix this 😞

**Comment by brianleroux** [comment]
ugh, oooook why does this work for me lol

**Comment by filmaj** [comment]
i ended up `npm install --save-dev aws-sdk` for my app (i.e. ran the install from `/Users/maj/src/arctonic/`) - that fixed me up.

**Comment by brianleroux** [comment]
does hydrate do --production ? (it probably should !)

**Comment by filmaj** [comment]
closing this, i think i was in a weird state where i had `@architect/architect` installed in my node_modules, but `@architect/cli` specified in my package.json...
