### ISSUE TITLE
Arc deploy failing with AWS CICD

### ISSUE THREAD

**Issue by Adnan029** [architect/functions#531]
**Describe the issue**
We have our application which has been developed with the Remix Architect feature and also running on AWS with local development using AWS credentials. We are trying to set up continuous integration so we are setting up an AWS CICD pipeline and facing some errors. 

Find the below error at deploy time using code build 

[Container] 2022/09/22 07:08:05 Running command arc deploy --production
--
76 | ·[?25l·[1A
77 | ·[?25l·[1A
78 | ·[?25l·[1A
79 | ·[?25l·[1A
80 | ·[?25l·[1A
81 | App ⌁ test-app
82 | Region ⌁ eu-west-1
83 | Profile ⌁ user
84 | Version ⌁ Architect 10.6.0
85 | cwd ⌁ /codebuild/output/src612014238/src
86 |  
87 | ·[?25l·[1A
88 | ·[?25l·[1A
89 | ⚬ Hydrate Hydrating dependencies in 1 path
90 | ⦾ Hydrate Hydrating server/·[1A
91 | ⦿ Hydrate Hydrating server/·[1A
92 | ⦿ Hydrate Hydrating server/·[1A
93 | ⦿ Hydrate Hydrating server/·[1A
94 | ⦾ Hydrate Hydrating server/·[1A
95 | ⊙ Hydrate Hydrating server/·[1A
96 | ⚬ Hydrate Hydrated server/
97 | × Error: Command failed: npm ci --production
98 | npm WARN config production Use `--omit=dev` instead.
99 | npm ERR! code EUSAGE
100 | npm ERR!
101 | npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
102 | npm ERR!
103 | npm ERR! Missing: aws-cloudwatch-log-browser@0.1.3 from lock file
104 | npm ERR! Missing: @types/node@12.20.55 from lock file
105 | npm ERR! Missing: axios@0.17.1 from lock file
106 | npm ERR! Missing: crypto-js@3.3.0 from lock file
107 | npm ERR! Missing: querystring@0.2.1 from lock file
108 | npm ERR! Missing: url@0.11.0 from lock file
109 | npm ERR! Missing: follow-redirects@1.15.2 from lock file
110 | npm ERR! Missing: is-buffer@1.1.6 from lock file
111 | npm ERR! Missing: punycode@1.3.2 from lock file
112 | npm ERR! Missing: querystring@0.2.0 from lock file
113 | npm ERR!
114 | npm ERR! Clean install a project
115 | npm ERR!
116 | npm ERR! Usage:
117 | npm ERR! npm ci
118 | npm ERR!
119 | npm ERR! Options:
120 | npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
121 | npm ERR! [--script-shell <script-shell>]
122 | npm ERR!
123 | npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
124 | npm ERR!
125 | npm ERR! Run "npm help ci" for more info
126 |  
127 | npm ERR! A complete log of this run can be found in:
128 | npm ERR!     /root/.npm/_logs/2022-09-22T07_08_07_339Z-debug-0.log
129 | Error:
130 | at ChildProcess.exithandler (node:child_process:398:12)
131 | at ChildProcess.emit (node:events:527:28)
132 | at ChildProcess.emit (node:domain:475:12)
133 | at maybeClose (node:internal/child_process:1092:16)
134 | at Socket.<anonymous> (node:internal/child_process:451:11)
135 | at Socket.emit (node:events:527:28)
136 | at Socket.emit (node:domain:475:12)
137 | at Pipe.<anonymous> (node:net:709:12)
138 | deploy failed! hydration_error
139 | Error: hydration_error
140 | at print (/usr/local/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/_printer.js:65:23)
141 | at /usr/local/lib/node_modules/@architect/architect/node_modules/@architect/hydrate/src/actions/install-update.js:29:7
142 | at ChildProcess.exithandler (node:child_process:406:5)
143 | at ChildProcess.emit (node:events:527:28)
144 | at ChildProcess.emit (node:domain:475:12)
145 | at maybeClose (node:internal/child_process:1092:16)
146 | at Socket.<anonymous> (node:internal/child_process:451:11)
147 | at Socket.emit (node:events:527:28)
148 | at Socket.emit (node:domain:475:12)
149 | at Pipe.<anonymous> (node:net:709:12)
150 | ·[?25h
151 | [Container] 2022/09/22 07:08:07 Command did not exit successfully arc deploy --production exit status 1
152 | [Container] 2022/09/22 07:08:07 Phase complete: BUILD State: FAILED
153 | [Container] 2022/09/22 07:08:07 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: arc deploy --production. Reason: exit status 1
```

**Comment by filmaj** [comment]
The underlying issue here is that your CI/CD pipeline is, understandably, trying to install your app dependencies by running `npm ci --production`. Here's the relevant output from your above logs:

```
96 | ⚬ Hydrate Hydrated server/
97 | × Error: Command failed: npm ci --production
98 | npm WARN config production Use --omit=dev instead.
99 | npm ERR! code EUSAGE
100 | npm ERR!
101 | npm ERR! npm ci can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with npm install before continuing.
```

From what I can tell, your app's `server` directory has `package.json` and `package-lock.json` contents that are out of sync. I don't think this is an arc issue. Closing this, but feel free to re-open or file a new issue if you feel otherwise.
